server:
  port: 9001
spring:
  servlet:
    multipart:
      max-file-size: 6400MB
      max-request-size: 6400MB
minio:
  endpoint: http://192.168.1.18:9111 #MinIO服务所在地址
  bucketName: jungle #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
